name = "nq0m-hamdash"
compatibility_date = "2025-04-01"
account_id = "1772cfe129955ef3e7c8114596902682"
pages_build_output_dir = "./dist/"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"

